// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWwu7dBWjDs8vC7Vu4XRknA9sRauyWd9k',
    appId: '1:698696626301:web:3534ed13a60d5325acc114',
    messagingSenderId: '698696626301',
    projectId: 'fisharoo-15fbc',
    authDomain: 'fisharoo-15fbc.firebaseapp.com',
    databaseURL: 'https://fisharoo-15fbc-default-rtdb.firebaseio.com',
    storageBucket: 'fisharoo-15fbc.appspot.com',
    measurementId: 'G-C3EY76MCQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA9TmnER0mPirUcnhgvwn480FkuX5y1b0',
    appId: '1:698696626301:android:2b2af93a5f12c2fbacc114',
    messagingSenderId: '698696626301',
    projectId: 'fisharoo-15fbc',
    databaseURL: 'https://fisharoo-15fbc-default-rtdb.firebaseio.com',
    storageBucket: 'fisharoo-15fbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8JuEEWuHXcc-IOWBDZW7CAUlyAC-ak0c',
    appId: '1:698696626301:ios:75d227e40ab9e1c3acc114',
    messagingSenderId: '698696626301',
    projectId: 'fisharoo-15fbc',
    databaseURL: 'https://fisharoo-15fbc-default-rtdb.firebaseio.com',
    storageBucket: 'fisharoo-15fbc.appspot.com',
    androidClientId: '698696626301-7hfm06mdiltoa6ar1796o2cc6l6hqjl8.apps.googleusercontent.com',
    iosClientId: '698696626301-tumvvdssn9s1qmn9rljd6f542jrk14c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishersc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8JuEEWuHXcc-IOWBDZW7CAUlyAC-ak0c',
    appId: '1:698696626301:ios:75d227e40ab9e1c3acc114',
    messagingSenderId: '698696626301',
    projectId: 'fisharoo-15fbc',
    databaseURL: 'https://fisharoo-15fbc-default-rtdb.firebaseio.com',
    storageBucket: 'fisharoo-15fbc.appspot.com',
    androidClientId: '698696626301-7hfm06mdiltoa6ar1796o2cc6l6hqjl8.apps.googleusercontent.com',
    iosClientId: '698696626301-tumvvdssn9s1qmn9rljd6f542jrk14c6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishersc',
  );
}
